spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${USER_NAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: NEVER
logging:
  level:
    root: debug